# Generated by Django 4.1.1 on 2022-10-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('header_image1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('header_image2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('payment_charge', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
